import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Social from "@/components/social";
import Head from "next/head";
import React from "react";

interface IMainLayout {
  children: React.ReactNode;
}

export default function MainLayout({ children }: IMainLayout) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      <Social />
      <Footer />
    </>
  );
}
